go
CREATE DATABASE dbQuiz2019
go
USE dbQuiz2019

CREATE TABLE tbProfessor (
	PROF_ID INT,
	PROF_RG CHAR(9) NOT NULL,
	PROF_NOME VARCHAR(50) NOT NULL,
	PROF_ISADMIN BIT NOT NULL,

	CONSTRAINT PK_tbProfessor PRIMARY KEY (PROF_ID),
	CONSTRAINT UQ_tbProfessor_PROF_RG UNIQUE (PROF_RG)
)

CREATE TABLE tbProf_Login (
	PROF_LOGIN_ID INT,
	PROF_ID INT NOT NULL,
	PROF_LOGIN_EMAIL VARCHAR(50) NOT NULL,
	PROF_LOGIN_PASS CHAR(64) NOT NULL,

	CONSTRAINT PK_tbProf_Login PRIMARY KEY (PROF_LOGIN_ID),
	CONSTRAINT UQ_tbProf_Login UNIQUE (PROF_LOGIN_EMAIL),
	CONSTRAINT FK_tbProf_Login_PROF_ID FOREIGN KEY (PROF_ID) REFERENCES tbProfessor,
)

CREATE TABLE tbTopico (
	T_ID INT,
	T_NOME VARCHAR(20) NOT NULL,
	
	CONSTRAINT PK_tbTopico PRIMARY KEY (T_ID),
	CONSTRAINT UQ_tbTopico_T_NOME UNIQUE (T_NOME)
)

CREATE TABLE tbDificuldade (
	DIF_ID INT,
	DIF_NOME VARCHAR(20) NOT NULL,
	DIF_VAL INT NOT NULL,

	CONSTRAINT PK_tbDificuldade PRIMARY KEY (DIF_ID),
	CONSTRAINT UQ_tbDificuldade_DIF_NOME UNIQUE (DIF_NOME),
	CONSTRAINT UQ_tbDificuldade_DIF_VAL UNIQUE (DIF_VAL)
)
CREATE TABLE tbImagem(
	IMG_ID int primary key,
	IMG_FILENAME varchar(256) not null ,
	IMG_DATA VARBINARY(max) not null
)
CREATE TABLE tbQuestao (
	Q_ID INT,
	DIF_ID INT NOT NULL,
	Q_TEXTO VARCHAR(600) NOT NULL,
	Q_IMG_ID int foreign key references tbImagem(IMG_ID),
	Q_TITULO VARCHAR(150) NOT NULL,
	Q_ISALTERNATIVE BIT NOT NULL,
	Q_TOPICO_ID INT NOT NULL,
	Q_DICA VARCHAR(150) NOT NULL,
	Q_ENABLED BIT NOT NULL

	CONSTRAINT PK_tbQuestao PRIMARY KEY (Q_ID),
	CONSTRAINT FK_tbQuestao_Q_TOPICO_ID FOREIGN KEY (Q_TOPICO_ID) REFERENCES tbTopico,
	CONSTRAINT FK_tbQuestao_DIF_ID FOREIGN KEY (DIF_ID) REFERENCES tbDificuldade
)

CREATE TABLE tbAlternativas (
	ALT_ID INT IDENTITY,
	ALT_Q_ID INT,
	ALT_CERTA BIT NOT NULL,
	ALT_TEXTO VARCHAR(100)

	CONSTRAINT PK_tbAlternativas PRIMARY KEY (ALT_ID),
	CONSTRAINT FK_tbAlternativas_ALT_CERTA FOREIGN KEY (ALT_Q_ID) REFERENCES tbQuestao
)

CREATE TABLE tbGrupo (
	GP_ID INT,
	GP_NOME VARCHAR(30) NOT NULL,
	GP_FRASE VARCHAR(75) NOT NULL,
	GP_COLOR CHAR(6) 

	CONSTRAINT PK_tbGrupo PRIMARY KEY (GP_ID),
	CONSTRAINT UQ_tbGrupo_GP_NOME UNIQUE (GP_NOME),
)

CREATE TABLE tbGrupo_Link(
	GP_ID INT,
	GP_LINK CHAR(16),

	CONSTRAINT FK_tbGrupo_Link_GP_ID FOREIGN KEY (GP_ID) REFERENCES tbGrupo,
	CONSTRAINT UQ_tbGrupo_Link_GP_LINK UNIQUE (GP_LINK),
	CONSTRAINT UQ_tbGrupo_Link_GP_ID UNIQUE (GP_ID)
)

CREATE TABLE tbParticipante (
	P_ID INT,
	P_RM CHAR(5) NOT NULL,
	P_NOME VARCHAR(50) NOT NULL,
	P_GP_ID INT,

	CONSTRAINT PK_tbParticipante PRIMARY KEY (P_ID),
	CONSTRAINT UQ_tbParticipante_P_RM UNIQUE (P_RM),
	CONSTRAINT FK_tbParticipante_P_GP_ID FOREIGN KEY (P_GP_ID) REFERENCES tbGrupo
)

CREATE TABLE tbGrupoAdmin(
	P_ID INT,
	GP_ID INT,

	CONSTRAINT FK_tbGrupoAdmin_P_ID FOREIGN KEY(P_ID) REFERENCES tbParticipante,
	CONSTRAINT UQ_tbGrupoAdmin_P_ID UNIQUE(P_ID),
	CONSTRAINT FK_tbGrupoAdmin_GP_ID FOREIGN KEY(GP_ID) REFERENCES tbGrupo,
	CONSTRAINT UQ_tbGrupoAdmin_GP_ID UNIQUE(GP_ID)
)

CREATE TABLE tbPart_Login (
	P_LOGIN_ID INT,
	P_ID INT NOT NULL,
	P_LOGIN_EMAIL VARCHAR(50) NOT NULL,
	P_LOGIN_PASS CHAR(64) not null,
	P_LOGIN_VERIFIED BIT NOT NULL,

	CONSTRAINT PK_tbPart_Login PRIMARY KEY (P_LOGIN_ID),
	CONSTRAINT UQ_tbPart_Login_P_LOGIN_EMAIL UNIQUE (P_LOGIN_EMAIL),
	CONSTRAINT FK_tbPart_Login_P_ID FOREIGN KEY (P_ID) REFERENCES tbParticipante
)

CREATE TABLE tbPart_Login_Verify(
	P_LOGIN_VERIFY_URL char(16),
	P_LOGIN_ID int not null

	CONSTRAINT PK_P_LOGIN_VERIFY_URL PRIMARY KEY(P_LOGIN_VERIFY_URL),
	CONSTRAINT FK_P_LOGIN_ID FOREIGN KEY (P_LOGIN_ID) REFERENCES tbPart_Login(P_LOGIN_ID),
	CONSTRAINT UQ_P_LOGIN_ID UNIQUE(P_LOGIN_ID)
)

CREATE TABLE tbToken_Senha (
	P_TOKEN CHAR(16) NOT NULL,
	P_LOGIN_EMAIL CHAR(64) NOT NULL,

	CONSTRAINT PK_tbToken_Senha_P_TOKEN PRIMARY KEY (P_TOKEN),
	CONSTRAINT UQ_tbToken_Senha_P_LOGIN_EMAIL UNIQUE (P_LOGIN_EMAIL)
)